### PR TITLE
Single websocket

### PR DESCRIPTION
**Pull request by mortonjack**
Probably added a bit too much to this PR. Apologies in advance. Should've done all the refactoring first, then moved to a single websocket later - but I worked backwards, moving to a single websocket, and fixing all the errors I could find.

Major changes are:
- Only one WebSocket is established between every pair of servers
- Every connection starts out in the uninitialised connection handler
- Client/Server handlers are different
- Improved some error handling

### CODE REVIEW

**Comment by Thomas-Frew** [comment]
It's a good PR but I agree the code frequency is too high for this. Next time remember to do 1 thing per PR.

**Comment by Thomas-Frew** [comment]
There's some code duplication when it comes to deserialising a message from JSON. In the future we will have a more complicated mechanism to verify a signed message. We should put this in a function that does all the verifiarion and returns message_type and message_data

**Comment by Thomas-Frew** [comment]
Using the SHA256 hash with message is shown to cause issues because the message can contain varying amounts of whitespace. I've had success storing the message_json as last_message, you can either change this or I will when this branch us pulled in

**Comment by Thomas-Frew** [comment]
I don't like the order these functions have been put in, it makes the code hardly to navigate. Group all client and all server message handling code in different groups. Put the client handlers above the functions that handle specific messages, and same for the server.

**Review by Thomas-Frew — CHANGES_REQUESTED** [review]
Please make the three improvements outlined.

**Comment by mortonjack** [comment]
> Using the SHA256 hash with message is shown to cause issues because the message can contain varying amounts of whitespace. I've had success storing the message_json as last_message, you can either change this or I will when this branch is pulled in

I figure this is temporary anyway. Duplicate messages should be allowed (e.g. `CLIENT_LIST_REQUEST`).

**Review by Thomas-Frew — APPROVED** [review]
Somehow I am remembering what rule of 5 is

**Pull request merged**
